services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: asignaciones_app
    #environment:
     # - APP_ENV=production
    #  - APP_KEY=${APP_KEY}   # Debes configurar esta clave en las variables de entorno
    restart: unless-stopped
    volumes:
      - ./storage/app/public:/var/www/html/storage/app/public
      - sessions:/var/www/html/storage/framework/sessions
    networks:
      - asignaciones_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: asignaciones_nginx
    volumes:
      - ./storage/app/public:/var/www/html/storage/app/public
    ports:
      - "8010:80"
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - asignaciones_network
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_app
    environment:
      - PMA_HOST=host.docker.internal
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8020:80"

networks:
  asignaciones_network:
    driver: bridge
volumes:
  sessions:
