services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: asignaciones_app
    #environment:
     # - APP_ENV=production
    #  - APP_KEY=${APP_KEY}   # Debes configurar esta clave en las variables de entorno
    restart: unless-stopped
    networks:
      - asignaciones_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: asignaciones_nginx
    ports:
      - "8010:80"
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - asignaciones_network
networks:
  asignaciones_network:
    driver: bridge
