services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        restart: unless-stopped
        container_name: asignaciones_app
        networks:
            - asignaciones_network
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 8010:80
        depends_on:
            - app
        restart: unless-stopped
        networks:
            - asignaciones_network
        container_name: asignaciones_nginx

networks:
    asignaciones_network:
        driver: bridge