version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ../:/app:cached
        restart: unless-stopped
        stdin_open: true
        tty: true
        depends_on:
            - db
    nginx:
        image: nginx:1.19.6-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../:/app:cached
        ports:
            - 8000:80
        depends_on:
            - app
        restart: unless-stopped
    db:
        image: mariadb:10.4
        restart: unless-stopped
        ports:
            - 3306:3306
        volumes:
            - mariadb-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: mariadb
            MYSQL_DATABASE: mariadb
            MYSQL_USER: mariadb
            MYSQL_PASSWORD: mariadb
volumes:
    mariadb-data:
